

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-test
    ports:
      - "5173:80"
    develop:
      watch:
        - path: .
          target: /app
          action: sync

  nginx:
    image: nginx:latest
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app